---
master_ip: "172.128.0.2" #"{{ hostvars[groups['k8ssvr'][0]]['ansible_default_ipv4'].address | default(groups['k8ssvr'][0]) }}"

kube_version: "v1.13.0"
service_cidr: "10.96.0.0/12"
pod_network_cidr: "10.244.0.0/16"

enable_dashboard: "yes"

kubeadmin_config: '/etc/kubernetes/admin.conf'
